// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: habit/v1/common.proto

package habitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExerciseKind int32

const (
	ExerciseKind_EXERCISE_KIND_UNSPECIFIED ExerciseKind = 0
	ExerciseKind_EXERCISE_KIND_TIMED       ExerciseKind = 1 // planks: timer + beep + difficulty
	ExerciseKind_EXERCISE_KIND_COUNTED     ExerciseKind = 2 // push-ups: count up + confirm + difficulty
	ExerciseKind_EXERCISE_KIND_LOGGED      ExerciseKind = 3 // kata: simple done + optional note
	ExerciseKind_EXERCISE_KIND_WEIGHTED    ExerciseKind = 4 // gym: sets/reps/weight + difficulty
)

// Enum value maps for ExerciseKind.
var (
	ExerciseKind_name = map[int32]string{
		0: "EXERCISE_KIND_UNSPECIFIED",
		1: "EXERCISE_KIND_TIMED",
		2: "EXERCISE_KIND_COUNTED",
		3: "EXERCISE_KIND_LOGGED",
		4: "EXERCISE_KIND_WEIGHTED",
	}
	ExerciseKind_value = map[string]int32{
		"EXERCISE_KIND_UNSPECIFIED": 0,
		"EXERCISE_KIND_TIMED":       1,
		"EXERCISE_KIND_COUNTED":     2,
		"EXERCISE_KIND_LOGGED":      3,
		"EXERCISE_KIND_WEIGHTED":    4,
	}
)

func (x ExerciseKind) Enum() *ExerciseKind {
	p := new(ExerciseKind)
	*p = x
	return p
}

func (x ExerciseKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExerciseKind) Descriptor() protoreflect.EnumDescriptor {
	return file_habit_v1_common_proto_enumTypes[0].Descriptor()
}

func (ExerciseKind) Type() protoreflect.EnumType {
	return &file_habit_v1_common_proto_enumTypes[0]
}

func (x ExerciseKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExerciseKind.Descriptor instead.
func (ExerciseKind) EnumDescriptor() ([]byte, []int) {
	return file_habit_v1_common_proto_rawDescGZIP(), []int{0}
}

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_IN_PROGRESS SessionStatus = 1
	SessionStatus_SESSION_STATUS_COMPLETED   SessionStatus = 2
	SessionStatus_SESSION_STATUS_SKIPPED     SessionStatus = 3
	SessionStatus_SESSION_STATUS_FAILED      SessionStatus = 4
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_IN_PROGRESS",
		2: "SESSION_STATUS_COMPLETED",
		3: "SESSION_STATUS_SKIPPED",
		4: "SESSION_STATUS_FAILED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_IN_PROGRESS": 1,
		"SESSION_STATUS_COMPLETED":   2,
		"SESSION_STATUS_SKIPPED":     3,
		"SESSION_STATUS_FAILED":      4,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_habit_v1_common_proto_enumTypes[1].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_habit_v1_common_proto_enumTypes[1]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_habit_v1_common_proto_rawDescGZIP(), []int{1}
}

type Difficulty int32

const (
	Difficulty_DIFFICULTY_UNSPECIFIED Difficulty = 0
	Difficulty_DIFFICULTY_EASY        Difficulty = 1
	Difficulty_DIFFICULTY_MODERATE    Difficulty = 2
	Difficulty_DIFFICULTY_HARD        Difficulty = 3
	Difficulty_DIFFICULTY_VERY_HARD   Difficulty = 4
	Difficulty_DIFFICULTY_FAILED      Difficulty = 5
)

// Enum value maps for Difficulty.
var (
	Difficulty_name = map[int32]string{
		0: "DIFFICULTY_UNSPECIFIED",
		1: "DIFFICULTY_EASY",
		2: "DIFFICULTY_MODERATE",
		3: "DIFFICULTY_HARD",
		4: "DIFFICULTY_VERY_HARD",
		5: "DIFFICULTY_FAILED",
	}
	Difficulty_value = map[string]int32{
		"DIFFICULTY_UNSPECIFIED": 0,
		"DIFFICULTY_EASY":        1,
		"DIFFICULTY_MODERATE":    2,
		"DIFFICULTY_HARD":        3,
		"DIFFICULTY_VERY_HARD":   4,
		"DIFFICULTY_FAILED":      5,
	}
)

func (x Difficulty) Enum() *Difficulty {
	p := new(Difficulty)
	*p = x
	return p
}

func (x Difficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Difficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_habit_v1_common_proto_enumTypes[2].Descriptor()
}

func (Difficulty) Type() protoreflect.EnumType {
	return &file_habit_v1_common_proto_enumTypes[2]
}

func (x Difficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Difficulty.Descriptor instead.
func (Difficulty) EnumDescriptor() ([]byte, []int) {
	return file_habit_v1_common_proto_rawDescGZIP(), []int{2}
}

var File_habit_v1_common_proto protoreflect.FileDescriptor

const file_habit_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15habit/v1/common.proto\x12\bhabit.v1*\x97\x01\n" +
	"\fExerciseKind\x12\x1d\n" +
	"\x19EXERCISE_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EXERCISE_KIND_TIMED\x10\x01\x12\x19\n" +
	"\x15EXERCISE_KIND_COUNTED\x10\x02\x12\x18\n" +
	"\x14EXERCISE_KIND_LOGGED\x10\x03\x12\x1a\n" +
	"\x16EXERCISE_KIND_WEIGHTED\x10\x04*\xa4\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSESSION_STATUS_IN_PROGRESS\x10\x01\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPLETED\x10\x02\x12\x1a\n" +
	"\x16SESSION_STATUS_SKIPPED\x10\x03\x12\x19\n" +
	"\x15SESSION_STATUS_FAILED\x10\x04*\x9c\x01\n" +
	"\n" +
	"Difficulty\x12\x1a\n" +
	"\x16DIFFICULTY_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fDIFFICULTY_EASY\x10\x01\x12\x17\n" +
	"\x13DIFFICULTY_MODERATE\x10\x02\x12\x13\n" +
	"\x0fDIFFICULTY_HARD\x10\x03\x12\x18\n" +
	"\x14DIFFICULTY_VERY_HARD\x10\x04\x12\x15\n" +
	"\x11DIFFICULTY_FAILED\x10\x05B\x9b\x01\n" +
	"\fcom.habit.v1B\vCommonProtoP\x01Z=github.com/geekgonecrazy/training-log/models/habit/v1;habitv1\xa2\x02\x03HXX\xaa\x02\bHabit.V1\xca\x02\bHabit\\V1\xe2\x02\x14Habit\\V1\\GPBMetadata\xea\x02\tHabit::V1b\x06proto3"

var (
	file_habit_v1_common_proto_rawDescOnce sync.Once
	file_habit_v1_common_proto_rawDescData []byte
)

func file_habit_v1_common_proto_rawDescGZIP() []byte {
	file_habit_v1_common_proto_rawDescOnce.Do(func() {
		file_habit_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_habit_v1_common_proto_rawDesc), len(file_habit_v1_common_proto_rawDesc)))
	})
	return file_habit_v1_common_proto_rawDescData
}

var file_habit_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_habit_v1_common_proto_goTypes = []any{
	(ExerciseKind)(0),  // 0: habit.v1.ExerciseKind
	(SessionStatus)(0), // 1: habit.v1.SessionStatus
	(Difficulty)(0),    // 2: habit.v1.Difficulty
}
var file_habit_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_habit_v1_common_proto_init() }
func file_habit_v1_common_proto_init() {
	if File_habit_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_habit_v1_common_proto_rawDesc), len(file_habit_v1_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_habit_v1_common_proto_goTypes,
		DependencyIndexes: file_habit_v1_common_proto_depIdxs,
		EnumInfos:         file_habit_v1_common_proto_enumTypes,
	}.Build()
	File_habit_v1_common_proto = out.File
	file_habit_v1_common_proto_goTypes = nil
	file_habit_v1_common_proto_depIdxs = nil
}
