// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: habit/v1/exercise.proto

package habitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exercise struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind      ExerciseKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=habit.v1.ExerciseKind" json:"kind,omitempty"`
	MachineId *int64                 `protobuf:"varint,4,opt,name=machine_id,json=machineId,proto3,oneof" json:"machine_id,omitempty"`
	// For COUNTED and WEIGHTED: target reps per set.
	GoalCount *int32 `protobuf:"varint,5,opt,name=goal_count,json=goalCount,proto3,oneof" json:"goal_count,omitempty"`
	// For TIMED: target seconds per set.
	GoalDurationSeconds *int32                 `protobuf:"varint,6,opt,name=goal_duration_seconds,json=goalDurationSeconds,proto3,oneof" json:"goal_duration_seconds,omitempty"`
	Instructions        string                 `protobuf:"bytes,7,opt,name=instructions,proto3" json:"instructions,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ArchivedAt          *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=archived_at,json=archivedAt,proto3,oneof" json:"archived_at,omitempty"`
	// Number of sets to perform per session. NULL or 0 means "1 set".
	GoalSets *int32 `protobuf:"varint,10,opt,name=goal_sets,json=goalSets,proto3,oneof" json:"goal_sets,omitempty"`
	// For WEIGHTED only: target weight in pounds.
	GoalWeightLb  *float64 `protobuf:"fixed64,11,opt,name=goal_weight_lb,json=goalWeightLb,proto3,oneof" json:"goal_weight_lb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exercise) Reset() {
	*x = Exercise{}
	mi := &file_habit_v1_exercise_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exercise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exercise) ProtoMessage() {}

func (x *Exercise) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_exercise_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exercise.ProtoReflect.Descriptor instead.
func (*Exercise) Descriptor() ([]byte, []int) {
	return file_habit_v1_exercise_proto_rawDescGZIP(), []int{0}
}

func (x *Exercise) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exercise) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Exercise) GetKind() ExerciseKind {
	if x != nil {
		return x.Kind
	}
	return ExerciseKind_EXERCISE_KIND_UNSPECIFIED
}

func (x *Exercise) GetMachineId() int64 {
	if x != nil && x.MachineId != nil {
		return *x.MachineId
	}
	return 0
}

func (x *Exercise) GetGoalCount() int32 {
	if x != nil && x.GoalCount != nil {
		return *x.GoalCount
	}
	return 0
}

func (x *Exercise) GetGoalDurationSeconds() int32 {
	if x != nil && x.GoalDurationSeconds != nil {
		return *x.GoalDurationSeconds
	}
	return 0
}

func (x *Exercise) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *Exercise) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Exercise) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *Exercise) GetGoalSets() int32 {
	if x != nil && x.GoalSets != nil {
		return *x.GoalSets
	}
	return 0
}

func (x *Exercise) GetGoalWeightLb() float64 {
	if x != nil && x.GoalWeightLb != nil {
		return *x.GoalWeightLb
	}
	return 0
}

type ListExercisesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeArchived bool                   `protobuf:"varint,1,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListExercisesRequest) Reset() {
	*x = ListExercisesRequest{}
	mi := &file_habit_v1_exercise_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExercisesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExercisesRequest) ProtoMessage() {}

func (x *ListExercisesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_exercise_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExercisesRequest.ProtoReflect.Descriptor instead.
func (*ListExercisesRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_exercise_proto_rawDescGZIP(), []int{1}
}

func (x *ListExercisesRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type ListExercisesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercises     []*Exercise            `protobuf:"bytes,1,rep,name=exercises,proto3" json:"exercises,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExercisesResponse) Reset() {
	*x = ListExercisesResponse{}
	mi := &file_habit_v1_exercise_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExercisesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExercisesResponse) ProtoMessage() {}

func (x *ListExercisesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_exercise_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExercisesResponse.ProtoReflect.Descriptor instead.
func (*ListExercisesResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_exercise_proto_rawDescGZIP(), []int{2}
}

func (x *ListExercisesResponse) GetExercises() []*Exercise {
	if x != nil {
		return x.Exercises
	}
	return nil
}

type GetExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseRequest) Reset() {
	*x = GetExerciseRequest{}
	mi := &file_habit_v1_exercise_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseRequest) ProtoMessage() {}

func (x *GetExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_exercise_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseRequest.ProtoReflect.Descriptor instead.
func (*GetExerciseRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_exercise_proto_rawDescGZIP(), []int{3}
}

func (x *GetExerciseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetExerciseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercise      *Exercise              `protobuf:"bytes,1,opt,name=exercise,proto3" json:"exercise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExerciseResponse) Reset() {
	*x = GetExerciseResponse{}
	mi := &file_habit_v1_exercise_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExerciseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExerciseResponse) ProtoMessage() {}

func (x *GetExerciseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_exercise_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExerciseResponse.ProtoReflect.Descriptor instead.
func (*GetExerciseResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_exercise_proto_rawDescGZIP(), []int{4}
}

func (x *GetExerciseResponse) GetExercise() *Exercise {
	if x != nil {
		return x.Exercise
	}
	return nil
}

type CreateExerciseRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind                ExerciseKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=habit.v1.ExerciseKind" json:"kind,omitempty"`
	MachineId           *int64                 `protobuf:"varint,3,opt,name=machine_id,json=machineId,proto3,oneof" json:"machine_id,omitempty"`
	GoalCount           *int32                 `protobuf:"varint,4,opt,name=goal_count,json=goalCount,proto3,oneof" json:"goal_count,omitempty"`
	GoalDurationSeconds *int32                 `protobuf:"varint,5,opt,name=goal_duration_seconds,json=goalDurationSeconds,proto3,oneof" json:"goal_duration_seconds,omitempty"`
	Instructions        string                 `protobuf:"bytes,6,opt,name=instructions,proto3" json:"instructions,omitempty"`
	GoalSets            *int32                 `protobuf:"varint,7,opt,name=goal_sets,json=goalSets,proto3,oneof" json:"goal_sets,omitempty"`
	GoalWeightLb        *float64               `protobuf:"fixed64,8,opt,name=goal_weight_lb,json=goalWeightLb,proto3,oneof" json:"goal_weight_lb,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateExerciseRequest) Reset() {
	*x = CreateExerciseRequest{}
	mi := &file_habit_v1_exercise_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExerciseRequest) ProtoMessage() {}

func (x *CreateExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_exercise_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExerciseRequest.ProtoReflect.Descriptor instead.
func (*CreateExerciseRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_exercise_proto_rawDescGZIP(), []int{5}
}

func (x *CreateExerciseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExerciseRequest) GetKind() ExerciseKind {
	if x != nil {
		return x.Kind
	}
	return ExerciseKind_EXERCISE_KIND_UNSPECIFIED
}

func (x *CreateExerciseRequest) GetMachineId() int64 {
	if x != nil && x.MachineId != nil {
		return *x.MachineId
	}
	return 0
}

func (x *CreateExerciseRequest) GetGoalCount() int32 {
	if x != nil && x.GoalCount != nil {
		return *x.GoalCount
	}
	return 0
}

func (x *CreateExerciseRequest) GetGoalDurationSeconds() int32 {
	if x != nil && x.GoalDurationSeconds != nil {
		return *x.GoalDurationSeconds
	}
	return 0
}

func (x *CreateExerciseRequest) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *CreateExerciseRequest) GetGoalSets() int32 {
	if x != nil && x.GoalSets != nil {
		return *x.GoalSets
	}
	return 0
}

func (x *CreateExerciseRequest) GetGoalWeightLb() float64 {
	if x != nil && x.GoalWeightLb != nil {
		return *x.GoalWeightLb
	}
	return 0
}

type CreateExerciseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercise      *Exercise              `protobuf:"bytes,1,opt,name=exercise,proto3" json:"exercise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExerciseResponse) Reset() {
	*x = CreateExerciseResponse{}
	mi := &file_habit_v1_exercise_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExerciseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExerciseResponse) ProtoMessage() {}

func (x *CreateExerciseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_exercise_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExerciseResponse.ProtoReflect.Descriptor instead.
func (*CreateExerciseResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_exercise_proto_rawDescGZIP(), []int{6}
}

func (x *CreateExerciseResponse) GetExercise() *Exercise {
	if x != nil {
		return x.Exercise
	}
	return nil
}

type UpdateExerciseRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind                ExerciseKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=habit.v1.ExerciseKind" json:"kind,omitempty"`
	MachineId           *int64                 `protobuf:"varint,4,opt,name=machine_id,json=machineId,proto3,oneof" json:"machine_id,omitempty"`
	GoalCount           *int32                 `protobuf:"varint,5,opt,name=goal_count,json=goalCount,proto3,oneof" json:"goal_count,omitempty"`
	GoalDurationSeconds *int32                 `protobuf:"varint,6,opt,name=goal_duration_seconds,json=goalDurationSeconds,proto3,oneof" json:"goal_duration_seconds,omitempty"`
	Instructions        string                 `protobuf:"bytes,7,opt,name=instructions,proto3" json:"instructions,omitempty"`
	GoalSets            *int32                 `protobuf:"varint,8,opt,name=goal_sets,json=goalSets,proto3,oneof" json:"goal_sets,omitempty"`
	GoalWeightLb        *float64               `protobuf:"fixed64,9,opt,name=goal_weight_lb,json=goalWeightLb,proto3,oneof" json:"goal_weight_lb,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateExerciseRequest) Reset() {
	*x = UpdateExerciseRequest{}
	mi := &file_habit_v1_exercise_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExerciseRequest) ProtoMessage() {}

func (x *UpdateExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_exercise_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExerciseRequest.ProtoReflect.Descriptor instead.
func (*UpdateExerciseRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_exercise_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateExerciseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateExerciseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateExerciseRequest) GetKind() ExerciseKind {
	if x != nil {
		return x.Kind
	}
	return ExerciseKind_EXERCISE_KIND_UNSPECIFIED
}

func (x *UpdateExerciseRequest) GetMachineId() int64 {
	if x != nil && x.MachineId != nil {
		return *x.MachineId
	}
	return 0
}

func (x *UpdateExerciseRequest) GetGoalCount() int32 {
	if x != nil && x.GoalCount != nil {
		return *x.GoalCount
	}
	return 0
}

func (x *UpdateExerciseRequest) GetGoalDurationSeconds() int32 {
	if x != nil && x.GoalDurationSeconds != nil {
		return *x.GoalDurationSeconds
	}
	return 0
}

func (x *UpdateExerciseRequest) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *UpdateExerciseRequest) GetGoalSets() int32 {
	if x != nil && x.GoalSets != nil {
		return *x.GoalSets
	}
	return 0
}

func (x *UpdateExerciseRequest) GetGoalWeightLb() float64 {
	if x != nil && x.GoalWeightLb != nil {
		return *x.GoalWeightLb
	}
	return 0
}

type UpdateExerciseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exercise      *Exercise              `protobuf:"bytes,1,opt,name=exercise,proto3" json:"exercise,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExerciseResponse) Reset() {
	*x = UpdateExerciseResponse{}
	mi := &file_habit_v1_exercise_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExerciseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExerciseResponse) ProtoMessage() {}

func (x *UpdateExerciseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_exercise_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExerciseResponse.ProtoReflect.Descriptor instead.
func (*UpdateExerciseResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_exercise_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateExerciseResponse) GetExercise() *Exercise {
	if x != nil {
		return x.Exercise
	}
	return nil
}

type ArchiveExerciseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveExerciseRequest) Reset() {
	*x = ArchiveExerciseRequest{}
	mi := &file_habit_v1_exercise_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveExerciseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveExerciseRequest) ProtoMessage() {}

func (x *ArchiveExerciseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_exercise_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveExerciseRequest.ProtoReflect.Descriptor instead.
func (*ArchiveExerciseRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_exercise_proto_rawDescGZIP(), []int{9}
}

func (x *ArchiveExerciseRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ArchiveExerciseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveExerciseResponse) Reset() {
	*x = ArchiveExerciseResponse{}
	mi := &file_habit_v1_exercise_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveExerciseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveExerciseResponse) ProtoMessage() {}

func (x *ArchiveExerciseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_exercise_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveExerciseResponse.ProtoReflect.Descriptor instead.
func (*ArchiveExerciseResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_exercise_proto_rawDescGZIP(), []int{10}
}

var File_habit_v1_exercise_proto protoreflect.FileDescriptor

const file_habit_v1_exercise_proto_rawDesc = "" +
	"\n" +
	"\x17habit/v1/exercise.proto\x12\bhabit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15habit/v1/common.proto\"\xb2\x04\n" +
	"\bExercise\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x16.habit.v1.ExerciseKindR\x04kind\x12\"\n" +
	"\n" +
	"machine_id\x18\x04 \x01(\x03H\x00R\tmachineId\x88\x01\x01\x12\"\n" +
	"\n" +
	"goal_count\x18\x05 \x01(\x05H\x01R\tgoalCount\x88\x01\x01\x127\n" +
	"\x15goal_duration_seconds\x18\x06 \x01(\x05H\x02R\x13goalDurationSeconds\x88\x01\x01\x12\"\n" +
	"\finstructions\x18\a \x01(\tR\finstructions\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\varchived_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x03R\n" +
	"archivedAt\x88\x01\x01\x12 \n" +
	"\tgoal_sets\x18\n" +
	" \x01(\x05H\x04R\bgoalSets\x88\x01\x01\x12)\n" +
	"\x0egoal_weight_lb\x18\v \x01(\x01H\x05R\fgoalWeightLb\x88\x01\x01B\r\n" +
	"\v_machine_idB\r\n" +
	"\v_goal_countB\x18\n" +
	"\x16_goal_duration_secondsB\x0e\n" +
	"\f_archived_atB\f\n" +
	"\n" +
	"_goal_setsB\x11\n" +
	"\x0f_goal_weight_lb\"A\n" +
	"\x14ListExercisesRequest\x12)\n" +
	"\x10include_archived\x18\x01 \x01(\bR\x0fincludeArchived\"I\n" +
	"\x15ListExercisesResponse\x120\n" +
	"\texercises\x18\x01 \x03(\v2\x12.habit.v1.ExerciseR\texercises\"$\n" +
	"\x12GetExerciseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\x13GetExerciseResponse\x12.\n" +
	"\bexercise\x18\x01 \x01(\v2\x12.habit.v1.ExerciseR\bexercise\"\xa2\x03\n" +
	"\x15CreateExerciseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.habit.v1.ExerciseKindR\x04kind\x12\"\n" +
	"\n" +
	"machine_id\x18\x03 \x01(\x03H\x00R\tmachineId\x88\x01\x01\x12\"\n" +
	"\n" +
	"goal_count\x18\x04 \x01(\x05H\x01R\tgoalCount\x88\x01\x01\x127\n" +
	"\x15goal_duration_seconds\x18\x05 \x01(\x05H\x02R\x13goalDurationSeconds\x88\x01\x01\x12\"\n" +
	"\finstructions\x18\x06 \x01(\tR\finstructions\x12 \n" +
	"\tgoal_sets\x18\a \x01(\x05H\x03R\bgoalSets\x88\x01\x01\x12)\n" +
	"\x0egoal_weight_lb\x18\b \x01(\x01H\x04R\fgoalWeightLb\x88\x01\x01B\r\n" +
	"\v_machine_idB\r\n" +
	"\v_goal_countB\x18\n" +
	"\x16_goal_duration_secondsB\f\n" +
	"\n" +
	"_goal_setsB\x11\n" +
	"\x0f_goal_weight_lb\"H\n" +
	"\x16CreateExerciseResponse\x12.\n" +
	"\bexercise\x18\x01 \x01(\v2\x12.habit.v1.ExerciseR\bexercise\"\xb2\x03\n" +
	"\x15UpdateExerciseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x16.habit.v1.ExerciseKindR\x04kind\x12\"\n" +
	"\n" +
	"machine_id\x18\x04 \x01(\x03H\x00R\tmachineId\x88\x01\x01\x12\"\n" +
	"\n" +
	"goal_count\x18\x05 \x01(\x05H\x01R\tgoalCount\x88\x01\x01\x127\n" +
	"\x15goal_duration_seconds\x18\x06 \x01(\x05H\x02R\x13goalDurationSeconds\x88\x01\x01\x12\"\n" +
	"\finstructions\x18\a \x01(\tR\finstructions\x12 \n" +
	"\tgoal_sets\x18\b \x01(\x05H\x03R\bgoalSets\x88\x01\x01\x12)\n" +
	"\x0egoal_weight_lb\x18\t \x01(\x01H\x04R\fgoalWeightLb\x88\x01\x01B\r\n" +
	"\v_machine_idB\r\n" +
	"\v_goal_countB\x18\n" +
	"\x16_goal_duration_secondsB\f\n" +
	"\n" +
	"_goal_setsB\x11\n" +
	"\x0f_goal_weight_lb\"H\n" +
	"\x16UpdateExerciseResponse\x12.\n" +
	"\bexercise\x18\x01 \x01(\v2\x12.habit.v1.ExerciseR\bexercise\"(\n" +
	"\x16ArchiveExerciseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x19\n" +
	"\x17ArchiveExerciseResponseB\x9d\x01\n" +
	"\fcom.habit.v1B\rExerciseProtoP\x01Z=github.com/geekgonecrazy/training-log/models/habit/v1;habitv1\xa2\x02\x03HXX\xaa\x02\bHabit.V1\xca\x02\bHabit\\V1\xe2\x02\x14Habit\\V1\\GPBMetadata\xea\x02\tHabit::V1b\x06proto3"

var (
	file_habit_v1_exercise_proto_rawDescOnce sync.Once
	file_habit_v1_exercise_proto_rawDescData []byte
)

func file_habit_v1_exercise_proto_rawDescGZIP() []byte {
	file_habit_v1_exercise_proto_rawDescOnce.Do(func() {
		file_habit_v1_exercise_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_habit_v1_exercise_proto_rawDesc), len(file_habit_v1_exercise_proto_rawDesc)))
	})
	return file_habit_v1_exercise_proto_rawDescData
}

var file_habit_v1_exercise_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_habit_v1_exercise_proto_goTypes = []any{
	(*Exercise)(nil),                // 0: habit.v1.Exercise
	(*ListExercisesRequest)(nil),    // 1: habit.v1.ListExercisesRequest
	(*ListExercisesResponse)(nil),   // 2: habit.v1.ListExercisesResponse
	(*GetExerciseRequest)(nil),      // 3: habit.v1.GetExerciseRequest
	(*GetExerciseResponse)(nil),     // 4: habit.v1.GetExerciseResponse
	(*CreateExerciseRequest)(nil),   // 5: habit.v1.CreateExerciseRequest
	(*CreateExerciseResponse)(nil),  // 6: habit.v1.CreateExerciseResponse
	(*UpdateExerciseRequest)(nil),   // 7: habit.v1.UpdateExerciseRequest
	(*UpdateExerciseResponse)(nil),  // 8: habit.v1.UpdateExerciseResponse
	(*ArchiveExerciseRequest)(nil),  // 9: habit.v1.ArchiveExerciseRequest
	(*ArchiveExerciseResponse)(nil), // 10: habit.v1.ArchiveExerciseResponse
	(ExerciseKind)(0),               // 11: habit.v1.ExerciseKind
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_habit_v1_exercise_proto_depIdxs = []int32{
	11, // 0: habit.v1.Exercise.kind:type_name -> habit.v1.ExerciseKind
	12, // 1: habit.v1.Exercise.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: habit.v1.Exercise.archived_at:type_name -> google.protobuf.Timestamp
	0,  // 3: habit.v1.ListExercisesResponse.exercises:type_name -> habit.v1.Exercise
	0,  // 4: habit.v1.GetExerciseResponse.exercise:type_name -> habit.v1.Exercise
	11, // 5: habit.v1.CreateExerciseRequest.kind:type_name -> habit.v1.ExerciseKind
	0,  // 6: habit.v1.CreateExerciseResponse.exercise:type_name -> habit.v1.Exercise
	11, // 7: habit.v1.UpdateExerciseRequest.kind:type_name -> habit.v1.ExerciseKind
	0,  // 8: habit.v1.UpdateExerciseResponse.exercise:type_name -> habit.v1.Exercise
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_habit_v1_exercise_proto_init() }
func file_habit_v1_exercise_proto_init() {
	if File_habit_v1_exercise_proto != nil {
		return
	}
	file_habit_v1_common_proto_init()
	file_habit_v1_exercise_proto_msgTypes[0].OneofWrappers = []any{}
	file_habit_v1_exercise_proto_msgTypes[5].OneofWrappers = []any{}
	file_habit_v1_exercise_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_habit_v1_exercise_proto_rawDesc), len(file_habit_v1_exercise_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_habit_v1_exercise_proto_goTypes,
		DependencyIndexes: file_habit_v1_exercise_proto_depIdxs,
		MessageInfos:      file_habit_v1_exercise_proto_msgTypes,
	}.Build()
	File_habit_v1_exercise_proto = out.File
	file_habit_v1_exercise_proto_goTypes = nil
	file_habit_v1_exercise_proto_depIdxs = nil
}
