// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: habit/v1/report.proto

package habitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExerciseRollup struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId        int64                  `protobuf:"varint,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	ExerciseName      string                 `protobuf:"bytes,2,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	Kind              ExerciseKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=habit.v1.ExerciseKind" json:"kind,omitempty"`
	SessionsTotal     int32                  `protobuf:"varint,4,opt,name=sessions_total,json=sessionsTotal,proto3" json:"sessions_total,omitempty"`
	SessionsCompleted int32                  `protobuf:"varint,5,opt,name=sessions_completed,json=sessionsCompleted,proto3" json:"sessions_completed,omitempty"`
	SessionsSkipped   int32                  `protobuf:"varint,6,opt,name=sessions_skipped,json=sessionsSkipped,proto3" json:"sessions_skipped,omitempty"`
	SessionsFailed    int32                  `protobuf:"varint,7,opt,name=sessions_failed,json=sessionsFailed,proto3" json:"sessions_failed,omitempty"`
	// Sum of count_completed across the period (counted exercises).
	TotalCount int32 `protobuf:"varint,8,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// Sum of duration_seconds across the period (timed exercises).
	TotalDurationSeconds int32 `protobuf:"varint,9,opt,name=total_duration_seconds,json=totalDurationSeconds,proto3" json:"total_duration_seconds,omitempty"`
	// Mean numeric difficulty (1=Easy..5=Failed) over completed sessions.
	// 0 if no completed sessions had a difficulty rating.
	AvgDifficulty float64 `protobuf:"fixed64,10,opt,name=avg_difficulty,json=avgDifficulty,proto3" json:"avg_difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseRollup) Reset() {
	*x = ExerciseRollup{}
	mi := &file_habit_v1_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseRollup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseRollup) ProtoMessage() {}

func (x *ExerciseRollup) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseRollup.ProtoReflect.Descriptor instead.
func (*ExerciseRollup) Descriptor() ([]byte, []int) {
	return file_habit_v1_report_proto_rawDescGZIP(), []int{0}
}

func (x *ExerciseRollup) GetExerciseId() int64 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

func (x *ExerciseRollup) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *ExerciseRollup) GetKind() ExerciseKind {
	if x != nil {
		return x.Kind
	}
	return ExerciseKind_EXERCISE_KIND_UNSPECIFIED
}

func (x *ExerciseRollup) GetSessionsTotal() int32 {
	if x != nil {
		return x.SessionsTotal
	}
	return 0
}

func (x *ExerciseRollup) GetSessionsCompleted() int32 {
	if x != nil {
		return x.SessionsCompleted
	}
	return 0
}

func (x *ExerciseRollup) GetSessionsSkipped() int32 {
	if x != nil {
		return x.SessionsSkipped
	}
	return 0
}

func (x *ExerciseRollup) GetSessionsFailed() int32 {
	if x != nil {
		return x.SessionsFailed
	}
	return 0
}

func (x *ExerciseRollup) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ExerciseRollup) GetTotalDurationSeconds() int32 {
	if x != nil {
		return x.TotalDurationSeconds
	}
	return 0
}

func (x *ExerciseRollup) GetAvgDifficulty() float64 {
	if x != nil {
		return x.AvgDifficulty
	}
	return 0
}

type PeriodReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Period identifier:
	//   - weekly: ISO week, e.g. "2026-W18"
	//   - monthly: "2026-05"
	Period        string            `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Rollups       []*ExerciseRollup `protobuf:"bytes,2,rep,name=rollups,proto3" json:"rollups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeriodReport) Reset() {
	*x = PeriodReport{}
	mi := &file_habit_v1_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeriodReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeriodReport) ProtoMessage() {}

func (x *PeriodReport) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeriodReport.ProtoReflect.Descriptor instead.
func (*PeriodReport) Descriptor() ([]byte, []int) {
	return file_habit_v1_report_proto_rawDescGZIP(), []int{1}
}

func (x *PeriodReport) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *PeriodReport) GetRollups() []*ExerciseRollup {
	if x != nil {
		return x.Rollups
	}
	return nil
}

type GetWeeklyReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ISO week, e.g. "2026-W18". If empty, current week.
	Week          string `protobuf:"bytes,1,opt,name=week,proto3" json:"week,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeeklyReportRequest) Reset() {
	*x = GetWeeklyReportRequest{}
	mi := &file_habit_v1_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeeklyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeeklyReportRequest) ProtoMessage() {}

func (x *GetWeeklyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeeklyReportRequest.ProtoReflect.Descriptor instead.
func (*GetWeeklyReportRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_report_proto_rawDescGZIP(), []int{2}
}

func (x *GetWeeklyReportRequest) GetWeek() string {
	if x != nil {
		return x.Week
	}
	return ""
}

type GetWeeklyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *PeriodReport          `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeeklyReportResponse) Reset() {
	*x = GetWeeklyReportResponse{}
	mi := &file_habit_v1_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeeklyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeeklyReportResponse) ProtoMessage() {}

func (x *GetWeeklyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeeklyReportResponse.ProtoReflect.Descriptor instead.
func (*GetWeeklyReportResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_report_proto_rawDescGZIP(), []int{3}
}

func (x *GetWeeklyReportResponse) GetReport() *PeriodReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type GetMonthlyReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// YYYY-MM. If empty, current month.
	Month         string `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyReportRequest) Reset() {
	*x = GetMonthlyReportRequest{}
	mi := &file_habit_v1_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyReportRequest) ProtoMessage() {}

func (x *GetMonthlyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyReportRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlyReportRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_report_proto_rawDescGZIP(), []int{4}
}

func (x *GetMonthlyReportRequest) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type GetMonthlyReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *PeriodReport          `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyReportResponse) Reset() {
	*x = GetMonthlyReportResponse{}
	mi := &file_habit_v1_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyReportResponse) ProtoMessage() {}

func (x *GetMonthlyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyReportResponse.ProtoReflect.Descriptor instead.
func (*GetMonthlyReportResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_report_proto_rawDescGZIP(), []int{5}
}

func (x *GetMonthlyReportResponse) GetReport() *PeriodReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type ProgressionSuggestion struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ExerciseId   int64                  `protobuf:"varint,1,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	ExerciseName string                 `protobuf:"bytes,2,opt,name=exercise_name,json=exerciseName,proto3" json:"exercise_name,omitempty"`
	Kind         ExerciseKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=habit.v1.ExerciseKind" json:"kind,omitempty"`
	// The current goal that should be considered for a bump.
	CurrentGoalCount           *int32 `protobuf:"varint,4,opt,name=current_goal_count,json=currentGoalCount,proto3,oneof" json:"current_goal_count,omitempty"`
	CurrentGoalDurationSeconds *int32 `protobuf:"varint,5,opt,name=current_goal_duration_seconds,json=currentGoalDurationSeconds,proto3,oneof" json:"current_goal_duration_seconds,omitempty"`
	// The number of recent sessions that met the threshold.
	SupportingSessions int32 `protobuf:"varint,6,opt,name=supporting_sessions,json=supportingSessions,proto3" json:"supporting_sessions,omitempty"`
	// Recommendation, e.g. "+2 reps" or "+5s". Free-text for UI.
	Recommendation string `protobuf:"bytes,7,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProgressionSuggestion) Reset() {
	*x = ProgressionSuggestion{}
	mi := &file_habit_v1_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressionSuggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressionSuggestion) ProtoMessage() {}

func (x *ProgressionSuggestion) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressionSuggestion.ProtoReflect.Descriptor instead.
func (*ProgressionSuggestion) Descriptor() ([]byte, []int) {
	return file_habit_v1_report_proto_rawDescGZIP(), []int{6}
}

func (x *ProgressionSuggestion) GetExerciseId() int64 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

func (x *ProgressionSuggestion) GetExerciseName() string {
	if x != nil {
		return x.ExerciseName
	}
	return ""
}

func (x *ProgressionSuggestion) GetKind() ExerciseKind {
	if x != nil {
		return x.Kind
	}
	return ExerciseKind_EXERCISE_KIND_UNSPECIFIED
}

func (x *ProgressionSuggestion) GetCurrentGoalCount() int32 {
	if x != nil && x.CurrentGoalCount != nil {
		return *x.CurrentGoalCount
	}
	return 0
}

func (x *ProgressionSuggestion) GetCurrentGoalDurationSeconds() int32 {
	if x != nil && x.CurrentGoalDurationSeconds != nil {
		return *x.CurrentGoalDurationSeconds
	}
	return 0
}

func (x *ProgressionSuggestion) GetSupportingSessions() int32 {
	if x != nil {
		return x.SupportingSessions
	}
	return 0
}

func (x *ProgressionSuggestion) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

type ListProgressionSuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProgressionSuggestionsRequest) Reset() {
	*x = ListProgressionSuggestionsRequest{}
	mi := &file_habit_v1_report_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgressionSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgressionSuggestionsRequest) ProtoMessage() {}

func (x *ListProgressionSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_report_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProgressionSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*ListProgressionSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_report_proto_rawDescGZIP(), []int{7}
}

type ListProgressionSuggestionsResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Suggestions   []*ProgressionSuggestion `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProgressionSuggestionsResponse) Reset() {
	*x = ListProgressionSuggestionsResponse{}
	mi := &file_habit_v1_report_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProgressionSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProgressionSuggestionsResponse) ProtoMessage() {}

func (x *ListProgressionSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_report_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProgressionSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*ListProgressionSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_report_proto_rawDescGZIP(), []int{8}
}

func (x *ListProgressionSuggestionsResponse) GetSuggestions() []*ProgressionSuggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_habit_v1_report_proto protoreflect.FileDescriptor

const file_habit_v1_report_proto_rawDesc = "" +
	"\n" +
	"\x15habit/v1/report.proto\x12\bhabit.v1\x1a\x15habit/v1/common.proto\"\xaa\x03\n" +
	"\x0eExerciseRollup\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\x03R\n" +
	"exerciseId\x12#\n" +
	"\rexercise_name\x18\x02 \x01(\tR\fexerciseName\x12*\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x16.habit.v1.ExerciseKindR\x04kind\x12%\n" +
	"\x0esessions_total\x18\x04 \x01(\x05R\rsessionsTotal\x12-\n" +
	"\x12sessions_completed\x18\x05 \x01(\x05R\x11sessionsCompleted\x12)\n" +
	"\x10sessions_skipped\x18\x06 \x01(\x05R\x0fsessionsSkipped\x12'\n" +
	"\x0fsessions_failed\x18\a \x01(\x05R\x0esessionsFailed\x12\x1f\n" +
	"\vtotal_count\x18\b \x01(\x05R\n" +
	"totalCount\x124\n" +
	"\x16total_duration_seconds\x18\t \x01(\x05R\x14totalDurationSeconds\x12%\n" +
	"\x0eavg_difficulty\x18\n" +
	" \x01(\x01R\ravgDifficulty\"Z\n" +
	"\fPeriodReport\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x122\n" +
	"\arollups\x18\x02 \x03(\v2\x18.habit.v1.ExerciseRollupR\arollups\",\n" +
	"\x16GetWeeklyReportRequest\x12\x12\n" +
	"\x04week\x18\x01 \x01(\tR\x04week\"I\n" +
	"\x17GetWeeklyReportResponse\x12.\n" +
	"\x06report\x18\x01 \x01(\v2\x16.habit.v1.PeriodReportR\x06report\"/\n" +
	"\x17GetMonthlyReportRequest\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\"J\n" +
	"\x18GetMonthlyReportResponse\x12.\n" +
	"\x06report\x18\x01 \x01(\v2\x16.habit.v1.PeriodReportR\x06report\"\x96\x03\n" +
	"\x15ProgressionSuggestion\x12\x1f\n" +
	"\vexercise_id\x18\x01 \x01(\x03R\n" +
	"exerciseId\x12#\n" +
	"\rexercise_name\x18\x02 \x01(\tR\fexerciseName\x12*\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x16.habit.v1.ExerciseKindR\x04kind\x121\n" +
	"\x12current_goal_count\x18\x04 \x01(\x05H\x00R\x10currentGoalCount\x88\x01\x01\x12F\n" +
	"\x1dcurrent_goal_duration_seconds\x18\x05 \x01(\x05H\x01R\x1acurrentGoalDurationSeconds\x88\x01\x01\x12/\n" +
	"\x13supporting_sessions\x18\x06 \x01(\x05R\x12supportingSessions\x12&\n" +
	"\x0erecommendation\x18\a \x01(\tR\x0erecommendationB\x15\n" +
	"\x13_current_goal_countB \n" +
	"\x1e_current_goal_duration_seconds\"#\n" +
	"!ListProgressionSuggestionsRequest\"g\n" +
	"\"ListProgressionSuggestionsResponse\x12A\n" +
	"\vsuggestions\x18\x01 \x03(\v2\x1f.habit.v1.ProgressionSuggestionR\vsuggestionsB\x9b\x01\n" +
	"\fcom.habit.v1B\vReportProtoP\x01Z=github.com/geekgonecrazy/training-log/models/habit/v1;habitv1\xa2\x02\x03HXX\xaa\x02\bHabit.V1\xca\x02\bHabit\\V1\xe2\x02\x14Habit\\V1\\GPBMetadata\xea\x02\tHabit::V1b\x06proto3"

var (
	file_habit_v1_report_proto_rawDescOnce sync.Once
	file_habit_v1_report_proto_rawDescData []byte
)

func file_habit_v1_report_proto_rawDescGZIP() []byte {
	file_habit_v1_report_proto_rawDescOnce.Do(func() {
		file_habit_v1_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_habit_v1_report_proto_rawDesc), len(file_habit_v1_report_proto_rawDesc)))
	})
	return file_habit_v1_report_proto_rawDescData
}

var file_habit_v1_report_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_habit_v1_report_proto_goTypes = []any{
	(*ExerciseRollup)(nil),                     // 0: habit.v1.ExerciseRollup
	(*PeriodReport)(nil),                       // 1: habit.v1.PeriodReport
	(*GetWeeklyReportRequest)(nil),             // 2: habit.v1.GetWeeklyReportRequest
	(*GetWeeklyReportResponse)(nil),            // 3: habit.v1.GetWeeklyReportResponse
	(*GetMonthlyReportRequest)(nil),            // 4: habit.v1.GetMonthlyReportRequest
	(*GetMonthlyReportResponse)(nil),           // 5: habit.v1.GetMonthlyReportResponse
	(*ProgressionSuggestion)(nil),              // 6: habit.v1.ProgressionSuggestion
	(*ListProgressionSuggestionsRequest)(nil),  // 7: habit.v1.ListProgressionSuggestionsRequest
	(*ListProgressionSuggestionsResponse)(nil), // 8: habit.v1.ListProgressionSuggestionsResponse
	(ExerciseKind)(0),                          // 9: habit.v1.ExerciseKind
}
var file_habit_v1_report_proto_depIdxs = []int32{
	9, // 0: habit.v1.ExerciseRollup.kind:type_name -> habit.v1.ExerciseKind
	0, // 1: habit.v1.PeriodReport.rollups:type_name -> habit.v1.ExerciseRollup
	1, // 2: habit.v1.GetWeeklyReportResponse.report:type_name -> habit.v1.PeriodReport
	1, // 3: habit.v1.GetMonthlyReportResponse.report:type_name -> habit.v1.PeriodReport
	9, // 4: habit.v1.ProgressionSuggestion.kind:type_name -> habit.v1.ExerciseKind
	6, // 5: habit.v1.ListProgressionSuggestionsResponse.suggestions:type_name -> habit.v1.ProgressionSuggestion
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_habit_v1_report_proto_init() }
func file_habit_v1_report_proto_init() {
	if File_habit_v1_report_proto != nil {
		return
	}
	file_habit_v1_common_proto_init()
	file_habit_v1_report_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_habit_v1_report_proto_rawDesc), len(file_habit_v1_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_habit_v1_report_proto_goTypes,
		DependencyIndexes: file_habit_v1_report_proto_depIdxs,
		MessageInfos:      file_habit_v1_report_proto_msgTypes,
	}.Build()
	File_habit_v1_report_proto = out.File
	file_habit_v1_report_proto_goTypes = nil
	file_habit_v1_report_proto_depIdxs = nil
}
