// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: habit/v1/routine.proto

package habitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoutineItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoutineId     int64                  `protobuf:"varint,2,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	ExerciseId    int64                  `protobuf:"varint,3,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutineItem) Reset() {
	*x = RoutineItem{}
	mi := &file_habit_v1_routine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineItem) ProtoMessage() {}

func (x *RoutineItem) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineItem.ProtoReflect.Descriptor instead.
func (*RoutineItem) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{0}
}

func (x *RoutineItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoutineItem) GetRoutineId() int64 {
	if x != nil {
		return x.RoutineId
	}
	return 0
}

func (x *RoutineItem) GetExerciseId() int64 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

func (x *RoutineItem) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type Routine struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ArchivedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=archived_at,json=archivedAt,proto3,oneof" json:"archived_at,omitempty"`
	Items      []*RoutineItem         `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	// When true, the runner walks one set at a time round-robin across items
	// (circuit / superset style). When false, each item is fully exhausted
	// before moving to the next.
	AlternateSets bool `protobuf:"varint,6,opt,name=alternate_sets,json=alternateSets,proto3" json:"alternate_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Routine) Reset() {
	*x = Routine{}
	mi := &file_habit_v1_routine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Routine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Routine) ProtoMessage() {}

func (x *Routine) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Routine.ProtoReflect.Descriptor instead.
func (*Routine) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{1}
}

func (x *Routine) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Routine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Routine) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Routine) GetArchivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArchivedAt
	}
	return nil
}

func (x *Routine) GetItems() []*RoutineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Routine) GetAlternateSets() bool {
	if x != nil {
		return x.AlternateSets
	}
	return false
}

type ListRoutinesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeArchived bool                   `protobuf:"varint,1,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListRoutinesRequest) Reset() {
	*x = ListRoutinesRequest{}
	mi := &file_habit_v1_routine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutinesRequest) ProtoMessage() {}

func (x *ListRoutinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutinesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutinesRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{2}
}

func (x *ListRoutinesRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type ListRoutinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routines      []*Routine             `protobuf:"bytes,1,rep,name=routines,proto3" json:"routines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutinesResponse) Reset() {
	*x = ListRoutinesResponse{}
	mi := &file_habit_v1_routine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutinesResponse) ProtoMessage() {}

func (x *ListRoutinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutinesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutinesResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{3}
}

func (x *ListRoutinesResponse) GetRoutines() []*Routine {
	if x != nil {
		return x.Routines
	}
	return nil
}

type GetRoutineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutineRequest) Reset() {
	*x = GetRoutineRequest{}
	mi := &file_habit_v1_routine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutineRequest) ProtoMessage() {}

func (x *GetRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutineRequest.ProtoReflect.Descriptor instead.
func (*GetRoutineRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoutineRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routine       *Routine               `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutineResponse) Reset() {
	*x = GetRoutineResponse{}
	mi := &file_habit_v1_routine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutineResponse) ProtoMessage() {}

func (x *GetRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutineResponse.ProtoReflect.Descriptor instead.
func (*GetRoutineResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoutineResponse) GetRoutine() *Routine {
	if x != nil {
		return x.Routine
	}
	return nil
}

type CreateRoutineRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Ordered list of exercise IDs that compose the routine.
	ExerciseIds   []int64 `protobuf:"varint,2,rep,packed,name=exercise_ids,json=exerciseIds,proto3" json:"exercise_ids,omitempty"`
	AlternateSets bool    `protobuf:"varint,3,opt,name=alternate_sets,json=alternateSets,proto3" json:"alternate_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoutineRequest) Reset() {
	*x = CreateRoutineRequest{}
	mi := &file_habit_v1_routine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoutineRequest) ProtoMessage() {}

func (x *CreateRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoutineRequest.ProtoReflect.Descriptor instead.
func (*CreateRoutineRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoutineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoutineRequest) GetExerciseIds() []int64 {
	if x != nil {
		return x.ExerciseIds
	}
	return nil
}

func (x *CreateRoutineRequest) GetAlternateSets() bool {
	if x != nil {
		return x.AlternateSets
	}
	return false
}

type CreateRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routine       *Routine               `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoutineResponse) Reset() {
	*x = CreateRoutineResponse{}
	mi := &file_habit_v1_routine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoutineResponse) ProtoMessage() {}

func (x *CreateRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoutineResponse.ProtoReflect.Descriptor instead.
func (*CreateRoutineResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRoutineResponse) GetRoutine() *Routine {
	if x != nil {
		return x.Routine
	}
	return nil
}

type UpdateRoutineRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// If non-empty, replaces the routine items in the given order.
	ExerciseIds   []int64 `protobuf:"varint,3,rep,packed,name=exercise_ids,json=exerciseIds,proto3" json:"exercise_ids,omitempty"`
	AlternateSets bool    `protobuf:"varint,4,opt,name=alternate_sets,json=alternateSets,proto3" json:"alternate_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoutineRequest) Reset() {
	*x = UpdateRoutineRequest{}
	mi := &file_habit_v1_routine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoutineRequest) ProtoMessage() {}

func (x *UpdateRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoutineRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoutineRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRoutineRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoutineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoutineRequest) GetExerciseIds() []int64 {
	if x != nil {
		return x.ExerciseIds
	}
	return nil
}

func (x *UpdateRoutineRequest) GetAlternateSets() bool {
	if x != nil {
		return x.AlternateSets
	}
	return false
}

type UpdateRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routine       *Routine               `protobuf:"bytes,1,opt,name=routine,proto3" json:"routine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoutineResponse) Reset() {
	*x = UpdateRoutineResponse{}
	mi := &file_habit_v1_routine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoutineResponse) ProtoMessage() {}

func (x *UpdateRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoutineResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoutineResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRoutineResponse) GetRoutine() *Routine {
	if x != nil {
		return x.Routine
	}
	return nil
}

type ArchiveRoutineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRoutineRequest) Reset() {
	*x = ArchiveRoutineRequest{}
	mi := &file_habit_v1_routine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRoutineRequest) ProtoMessage() {}

func (x *ArchiveRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRoutineRequest.ProtoReflect.Descriptor instead.
func (*ArchiveRoutineRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{10}
}

func (x *ArchiveRoutineRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ArchiveRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveRoutineResponse) Reset() {
	*x = ArchiveRoutineResponse{}
	mi := &file_habit_v1_routine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveRoutineResponse) ProtoMessage() {}

func (x *ArchiveRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveRoutineResponse.ProtoReflect.Descriptor instead.
func (*ArchiveRoutineResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{11}
}

type RoutineRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoutineId     int64                  `protobuf:"varint,2,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=ended_at,json=endedAt,proto3,oneof" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutineRun) Reset() {
	*x = RoutineRun{}
	mi := &file_habit_v1_routine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutineRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutineRun) ProtoMessage() {}

func (x *RoutineRun) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutineRun.ProtoReflect.Descriptor instead.
func (*RoutineRun) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{12}
}

func (x *RoutineRun) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoutineRun) GetRoutineId() int64 {
	if x != nil {
		return x.RoutineId
	}
	return 0
}

func (x *RoutineRun) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RoutineRun) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

type StartRoutineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutineId     int64                  `protobuf:"varint,1,opt,name=routine_id,json=routineId,proto3" json:"routine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRoutineRequest) Reset() {
	*x = StartRoutineRequest{}
	mi := &file_habit_v1_routine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRoutineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRoutineRequest) ProtoMessage() {}

func (x *StartRoutineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRoutineRequest.ProtoReflect.Descriptor instead.
func (*StartRoutineRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{13}
}

func (x *StartRoutineRequest) GetRoutineId() int64 {
	if x != nil {
		return x.RoutineId
	}
	return 0
}

type StartRoutineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *RoutineRun            `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRoutineResponse) Reset() {
	*x = StartRoutineResponse{}
	mi := &file_habit_v1_routine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRoutineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRoutineResponse) ProtoMessage() {}

func (x *StartRoutineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRoutineResponse.ProtoReflect.Descriptor instead.
func (*StartRoutineResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{14}
}

func (x *StartRoutineResponse) GetRun() *RoutineRun {
	if x != nil {
		return x.Run
	}
	return nil
}

type EndRoutineRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         int64                  `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndRoutineRunRequest) Reset() {
	*x = EndRoutineRunRequest{}
	mi := &file_habit_v1_routine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndRoutineRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRoutineRunRequest) ProtoMessage() {}

func (x *EndRoutineRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRoutineRunRequest.ProtoReflect.Descriptor instead.
func (*EndRoutineRunRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{15}
}

func (x *EndRoutineRunRequest) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

type EndRoutineRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *RoutineRun            `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndRoutineRunResponse) Reset() {
	*x = EndRoutineRunResponse{}
	mi := &file_habit_v1_routine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndRoutineRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRoutineRunResponse) ProtoMessage() {}

func (x *EndRoutineRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_routine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRoutineRunResponse.ProtoReflect.Descriptor instead.
func (*EndRoutineRunResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_routine_proto_rawDescGZIP(), []int{16}
}

func (x *EndRoutineRunResponse) GetRun() *RoutineRun {
	if x != nil {
		return x.Run
	}
	return nil
}

var File_habit_v1_routine_proto protoreflect.FileDescriptor

const file_habit_v1_routine_proto_rawDesc = "" +
	"\n" +
	"\x16habit/v1/routine.proto\x12\bhabit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n" +
	"\vRoutineItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x02 \x01(\x03R\troutineId\x12\x1f\n" +
	"\vexercise_id\x18\x03 \x01(\x03R\n" +
	"exerciseId\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"\x8e\x02\n" +
	"\aRoutine\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\varchived_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"archivedAt\x88\x01\x01\x12+\n" +
	"\x05items\x18\x05 \x03(\v2\x15.habit.v1.RoutineItemR\x05items\x12%\n" +
	"\x0ealternate_sets\x18\x06 \x01(\bR\ralternateSetsB\x0e\n" +
	"\f_archived_at\"@\n" +
	"\x13ListRoutinesRequest\x12)\n" +
	"\x10include_archived\x18\x01 \x01(\bR\x0fincludeArchived\"E\n" +
	"\x14ListRoutinesResponse\x12-\n" +
	"\broutines\x18\x01 \x03(\v2\x11.habit.v1.RoutineR\broutines\"#\n" +
	"\x11GetRoutineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\x12GetRoutineResponse\x12+\n" +
	"\aroutine\x18\x01 \x01(\v2\x11.habit.v1.RoutineR\aroutine\"t\n" +
	"\x14CreateRoutineRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fexercise_ids\x18\x02 \x03(\x03R\vexerciseIds\x12%\n" +
	"\x0ealternate_sets\x18\x03 \x01(\bR\ralternateSets\"D\n" +
	"\x15CreateRoutineResponse\x12+\n" +
	"\aroutine\x18\x01 \x01(\v2\x11.habit.v1.RoutineR\aroutine\"\x84\x01\n" +
	"\x14UpdateRoutineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fexercise_ids\x18\x03 \x03(\x03R\vexerciseIds\x12%\n" +
	"\x0ealternate_sets\x18\x04 \x01(\bR\ralternateSets\"D\n" +
	"\x15UpdateRoutineResponse\x12+\n" +
	"\aroutine\x18\x01 \x01(\v2\x11.habit.v1.RoutineR\aroutine\"'\n" +
	"\x15ArchiveRoutineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x18\n" +
	"\x16ArchiveRoutineResponse\"\xbf\x01\n" +
	"\n" +
	"RoutineRun\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x02 \x01(\x03R\troutineId\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12:\n" +
	"\bended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\aendedAt\x88\x01\x01B\v\n" +
	"\t_ended_at\"4\n" +
	"\x13StartRoutineRequest\x12\x1d\n" +
	"\n" +
	"routine_id\x18\x01 \x01(\x03R\troutineId\">\n" +
	"\x14StartRoutineResponse\x12&\n" +
	"\x03run\x18\x01 \x01(\v2\x14.habit.v1.RoutineRunR\x03run\"-\n" +
	"\x14EndRoutineRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x03R\x05runId\"?\n" +
	"\x15EndRoutineRunResponse\x12&\n" +
	"\x03run\x18\x01 \x01(\v2\x14.habit.v1.RoutineRunR\x03runB\x9c\x01\n" +
	"\fcom.habit.v1B\fRoutineProtoP\x01Z=github.com/geekgonecrazy/training-log/models/habit/v1;habitv1\xa2\x02\x03HXX\xaa\x02\bHabit.V1\xca\x02\bHabit\\V1\xe2\x02\x14Habit\\V1\\GPBMetadata\xea\x02\tHabit::V1b\x06proto3"

var (
	file_habit_v1_routine_proto_rawDescOnce sync.Once
	file_habit_v1_routine_proto_rawDescData []byte
)

func file_habit_v1_routine_proto_rawDescGZIP() []byte {
	file_habit_v1_routine_proto_rawDescOnce.Do(func() {
		file_habit_v1_routine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_habit_v1_routine_proto_rawDesc), len(file_habit_v1_routine_proto_rawDesc)))
	})
	return file_habit_v1_routine_proto_rawDescData
}

var file_habit_v1_routine_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_habit_v1_routine_proto_goTypes = []any{
	(*RoutineItem)(nil),            // 0: habit.v1.RoutineItem
	(*Routine)(nil),                // 1: habit.v1.Routine
	(*ListRoutinesRequest)(nil),    // 2: habit.v1.ListRoutinesRequest
	(*ListRoutinesResponse)(nil),   // 3: habit.v1.ListRoutinesResponse
	(*GetRoutineRequest)(nil),      // 4: habit.v1.GetRoutineRequest
	(*GetRoutineResponse)(nil),     // 5: habit.v1.GetRoutineResponse
	(*CreateRoutineRequest)(nil),   // 6: habit.v1.CreateRoutineRequest
	(*CreateRoutineResponse)(nil),  // 7: habit.v1.CreateRoutineResponse
	(*UpdateRoutineRequest)(nil),   // 8: habit.v1.UpdateRoutineRequest
	(*UpdateRoutineResponse)(nil),  // 9: habit.v1.UpdateRoutineResponse
	(*ArchiveRoutineRequest)(nil),  // 10: habit.v1.ArchiveRoutineRequest
	(*ArchiveRoutineResponse)(nil), // 11: habit.v1.ArchiveRoutineResponse
	(*RoutineRun)(nil),             // 12: habit.v1.RoutineRun
	(*StartRoutineRequest)(nil),    // 13: habit.v1.StartRoutineRequest
	(*StartRoutineResponse)(nil),   // 14: habit.v1.StartRoutineResponse
	(*EndRoutineRunRequest)(nil),   // 15: habit.v1.EndRoutineRunRequest
	(*EndRoutineRunResponse)(nil),  // 16: habit.v1.EndRoutineRunResponse
	(*timestamppb.Timestamp)(nil),  // 17: google.protobuf.Timestamp
}
var file_habit_v1_routine_proto_depIdxs = []int32{
	17, // 0: habit.v1.Routine.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: habit.v1.Routine.archived_at:type_name -> google.protobuf.Timestamp
	0,  // 2: habit.v1.Routine.items:type_name -> habit.v1.RoutineItem
	1,  // 3: habit.v1.ListRoutinesResponse.routines:type_name -> habit.v1.Routine
	1,  // 4: habit.v1.GetRoutineResponse.routine:type_name -> habit.v1.Routine
	1,  // 5: habit.v1.CreateRoutineResponse.routine:type_name -> habit.v1.Routine
	1,  // 6: habit.v1.UpdateRoutineResponse.routine:type_name -> habit.v1.Routine
	17, // 7: habit.v1.RoutineRun.started_at:type_name -> google.protobuf.Timestamp
	17, // 8: habit.v1.RoutineRun.ended_at:type_name -> google.protobuf.Timestamp
	12, // 9: habit.v1.StartRoutineResponse.run:type_name -> habit.v1.RoutineRun
	12, // 10: habit.v1.EndRoutineRunResponse.run:type_name -> habit.v1.RoutineRun
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_habit_v1_routine_proto_init() }
func file_habit_v1_routine_proto_init() {
	if File_habit_v1_routine_proto != nil {
		return
	}
	file_habit_v1_routine_proto_msgTypes[1].OneofWrappers = []any{}
	file_habit_v1_routine_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_habit_v1_routine_proto_rawDesc), len(file_habit_v1_routine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_habit_v1_routine_proto_goTypes,
		DependencyIndexes: file_habit_v1_routine_proto_depIdxs,
		MessageInfos:      file_habit_v1_routine_proto_msgTypes,
	}.Build()
	File_habit_v1_routine_proto = out.File
	file_habit_v1_routine_proto_goTypes = nil
	file_habit_v1_routine_proto_depIdxs = nil
}
