// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: habit/v1/service.proto

package habitv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_habit_v1_service_proto protoreflect.FileDescriptor

const file_habit_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16habit/v1/service.proto\x12\bhabit.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x13habit/v1/auth.proto\x1a\x17habit/v1/exercise.proto\x1a\x16habit/v1/machine.proto\x1a\x15habit/v1/report.proto\x1a\x16habit/v1/routine.proto\x1a\x16habit/v1/session.proto2\xbf\x03\n" +
	"\vAuthService\x12_\n" +
	"\bRegister\x12\x19.habit.v1.RegisterRequest\x1a\x1a.habit.v1.RegisterResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12S\n" +
	"\x05Login\x12\x16.habit.v1.LoginRequest\x1a\x17.habit.v1.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12[\n" +
	"\aRefresh\x12\x18.habit.v1.RefreshRequest\x1a\x19.habit.v1.RefreshResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/auth/refresh\x12W\n" +
	"\x06Logout\x12\x17.habit.v1.LogoutRequest\x1a\x18.habit.v1.LogoutResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logout\x12D\n" +
	"\x02Me\x12\x13.habit.v1.MeRequest\x1a\x14.habit.v1.MeResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/auth/me2\x81\x15\n" +
	"\fHabitService\x12c\n" +
	"\fListMachines\x12\x1d.habit.v1.ListMachinesRequest\x1a\x1e.habit.v1.ListMachinesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/machines\x12b\n" +
	"\n" +
	"GetMachine\x12\x1b.habit.v1.GetMachineRequest\x1a\x1c.habit.v1.GetMachineResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/machines/{id}\x12i\n" +
	"\rCreateMachine\x12\x1e.habit.v1.CreateMachineRequest\x1a\x1f.habit.v1.CreateMachineResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/machines\x12n\n" +
	"\rUpdateMachine\x12\x1e.habit.v1.UpdateMachineRequest\x1a\x1f.habit.v1.UpdateMachineResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/machines/{id}\x12k\n" +
	"\rDeleteMachine\x12\x1e.habit.v1.DeleteMachineRequest\x1a\x1f.habit.v1.DeleteMachineResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/machines/{id}\x12g\n" +
	"\rListExercises\x12\x1e.habit.v1.ListExercisesRequest\x1a\x1f.habit.v1.ListExercisesResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/exercises\x12f\n" +
	"\vGetExercise\x12\x1c.habit.v1.GetExerciseRequest\x1a\x1d.habit.v1.GetExerciseResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/exercises/{id}\x12m\n" +
	"\x0eCreateExercise\x12\x1f.habit.v1.CreateExerciseRequest\x1a .habit.v1.CreateExerciseResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/exercises\x12r\n" +
	"\x0eUpdateExercise\x12\x1f.habit.v1.UpdateExerciseRequest\x1a .habit.v1.UpdateExerciseResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/exercises/{id}\x12r\n" +
	"\x0fArchiveExercise\x12 .habit.v1.ArchiveExerciseRequest\x1a!.habit.v1.ArchiveExerciseResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/exercises/{id}\x12c\n" +
	"\fListRoutines\x12\x1d.habit.v1.ListRoutinesRequest\x1a\x1e.habit.v1.ListRoutinesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/routines\x12b\n" +
	"\n" +
	"GetRoutine\x12\x1b.habit.v1.GetRoutineRequest\x1a\x1c.habit.v1.GetRoutineResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/routines/{id}\x12i\n" +
	"\rCreateRoutine\x12\x1e.habit.v1.CreateRoutineRequest\x1a\x1f.habit.v1.CreateRoutineResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/routines\x12n\n" +
	"\rUpdateRoutine\x12\x1e.habit.v1.UpdateRoutineRequest\x1a\x1f.habit.v1.UpdateRoutineResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/routines/{id}\x12n\n" +
	"\x0eArchiveRoutine\x12\x1f.habit.v1.ArchiveRoutineRequest\x1a .habit.v1.ArchiveRoutineResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/routines/{id}\x12y\n" +
	"\fStartRoutine\x12\x1d.habit.v1.StartRoutineRequest\x1a\x1e.habit.v1.StartRoutineResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/routines/{routine_id}:start\x12z\n" +
	"\rEndRoutineRun\x12\x1e.habit.v1.EndRoutineRunRequest\x1a\x1f.habit.v1.EndRoutineRunResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/routine-runs/{run_id}:end\x12`\n" +
	"\n" +
	"LogSession\x12\x1b.habit.v1.LogSessionRequest\x1a\x1c.habit.v1.LogSessionResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/sessions\x12c\n" +
	"\fListSessions\x12\x1d.habit.v1.ListSessionsRequest\x1a\x1e.habit.v1.ListSessionsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/sessions\x12n\n" +
	"\rUpdateSession\x12\x1e.habit.v1.UpdateSessionRequest\x1a\x1f.habit.v1.UpdateSessionResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/v1/sessions/{id}\x12k\n" +
	"\rDeleteSession\x12\x1e.habit.v1.DeleteSessionRequest\x1a\x1f.habit.v1.DeleteSessionResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/sessions/{id}\x12r\n" +
	"\x0fGetWeeklyReport\x12 .habit.v1.GetWeeklyReportRequest\x1a!.habit.v1.GetWeeklyReportResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/reports/weekly\x12v\n" +
	"\x10GetMonthlyReport\x12!.habit.v1.GetMonthlyReportRequest\x1a\".habit.v1.GetMonthlyReportResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/reports/monthly\x12\x9c\x01\n" +
	"\x1aListProgressionSuggestions\x12+.habit.v1.ListProgressionSuggestionsRequest\x1a,.habit.v1.ListProgressionSuggestionsResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/progression-suggestionsB\x9c\x01\n" +
	"\fcom.habit.v1B\fServiceProtoP\x01Z=github.com/geekgonecrazy/training-log/models/habit/v1;habitv1\xa2\x02\x03HXX\xaa\x02\bHabit.V1\xca\x02\bHabit\\V1\xe2\x02\x14Habit\\V1\\GPBMetadata\xea\x02\tHabit::V1b\x06proto3"

var file_habit_v1_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),                    // 0: habit.v1.RegisterRequest
	(*LoginRequest)(nil),                       // 1: habit.v1.LoginRequest
	(*RefreshRequest)(nil),                     // 2: habit.v1.RefreshRequest
	(*LogoutRequest)(nil),                      // 3: habit.v1.LogoutRequest
	(*MeRequest)(nil),                          // 4: habit.v1.MeRequest
	(*ListMachinesRequest)(nil),                // 5: habit.v1.ListMachinesRequest
	(*GetMachineRequest)(nil),                  // 6: habit.v1.GetMachineRequest
	(*CreateMachineRequest)(nil),               // 7: habit.v1.CreateMachineRequest
	(*UpdateMachineRequest)(nil),               // 8: habit.v1.UpdateMachineRequest
	(*DeleteMachineRequest)(nil),               // 9: habit.v1.DeleteMachineRequest
	(*ListExercisesRequest)(nil),               // 10: habit.v1.ListExercisesRequest
	(*GetExerciseRequest)(nil),                 // 11: habit.v1.GetExerciseRequest
	(*CreateExerciseRequest)(nil),              // 12: habit.v1.CreateExerciseRequest
	(*UpdateExerciseRequest)(nil),              // 13: habit.v1.UpdateExerciseRequest
	(*ArchiveExerciseRequest)(nil),             // 14: habit.v1.ArchiveExerciseRequest
	(*ListRoutinesRequest)(nil),                // 15: habit.v1.ListRoutinesRequest
	(*GetRoutineRequest)(nil),                  // 16: habit.v1.GetRoutineRequest
	(*CreateRoutineRequest)(nil),               // 17: habit.v1.CreateRoutineRequest
	(*UpdateRoutineRequest)(nil),               // 18: habit.v1.UpdateRoutineRequest
	(*ArchiveRoutineRequest)(nil),              // 19: habit.v1.ArchiveRoutineRequest
	(*StartRoutineRequest)(nil),                // 20: habit.v1.StartRoutineRequest
	(*EndRoutineRunRequest)(nil),               // 21: habit.v1.EndRoutineRunRequest
	(*LogSessionRequest)(nil),                  // 22: habit.v1.LogSessionRequest
	(*ListSessionsRequest)(nil),                // 23: habit.v1.ListSessionsRequest
	(*UpdateSessionRequest)(nil),               // 24: habit.v1.UpdateSessionRequest
	(*DeleteSessionRequest)(nil),               // 25: habit.v1.DeleteSessionRequest
	(*GetWeeklyReportRequest)(nil),             // 26: habit.v1.GetWeeklyReportRequest
	(*GetMonthlyReportRequest)(nil),            // 27: habit.v1.GetMonthlyReportRequest
	(*ListProgressionSuggestionsRequest)(nil),  // 28: habit.v1.ListProgressionSuggestionsRequest
	(*RegisterResponse)(nil),                   // 29: habit.v1.RegisterResponse
	(*LoginResponse)(nil),                      // 30: habit.v1.LoginResponse
	(*RefreshResponse)(nil),                    // 31: habit.v1.RefreshResponse
	(*LogoutResponse)(nil),                     // 32: habit.v1.LogoutResponse
	(*MeResponse)(nil),                         // 33: habit.v1.MeResponse
	(*ListMachinesResponse)(nil),               // 34: habit.v1.ListMachinesResponse
	(*GetMachineResponse)(nil),                 // 35: habit.v1.GetMachineResponse
	(*CreateMachineResponse)(nil),              // 36: habit.v1.CreateMachineResponse
	(*UpdateMachineResponse)(nil),              // 37: habit.v1.UpdateMachineResponse
	(*DeleteMachineResponse)(nil),              // 38: habit.v1.DeleteMachineResponse
	(*ListExercisesResponse)(nil),              // 39: habit.v1.ListExercisesResponse
	(*GetExerciseResponse)(nil),                // 40: habit.v1.GetExerciseResponse
	(*CreateExerciseResponse)(nil),             // 41: habit.v1.CreateExerciseResponse
	(*UpdateExerciseResponse)(nil),             // 42: habit.v1.UpdateExerciseResponse
	(*ArchiveExerciseResponse)(nil),            // 43: habit.v1.ArchiveExerciseResponse
	(*ListRoutinesResponse)(nil),               // 44: habit.v1.ListRoutinesResponse
	(*GetRoutineResponse)(nil),                 // 45: habit.v1.GetRoutineResponse
	(*CreateRoutineResponse)(nil),              // 46: habit.v1.CreateRoutineResponse
	(*UpdateRoutineResponse)(nil),              // 47: habit.v1.UpdateRoutineResponse
	(*ArchiveRoutineResponse)(nil),             // 48: habit.v1.ArchiveRoutineResponse
	(*StartRoutineResponse)(nil),               // 49: habit.v1.StartRoutineResponse
	(*EndRoutineRunResponse)(nil),              // 50: habit.v1.EndRoutineRunResponse
	(*LogSessionResponse)(nil),                 // 51: habit.v1.LogSessionResponse
	(*ListSessionsResponse)(nil),               // 52: habit.v1.ListSessionsResponse
	(*UpdateSessionResponse)(nil),              // 53: habit.v1.UpdateSessionResponse
	(*DeleteSessionResponse)(nil),              // 54: habit.v1.DeleteSessionResponse
	(*GetWeeklyReportResponse)(nil),            // 55: habit.v1.GetWeeklyReportResponse
	(*GetMonthlyReportResponse)(nil),           // 56: habit.v1.GetMonthlyReportResponse
	(*ListProgressionSuggestionsResponse)(nil), // 57: habit.v1.ListProgressionSuggestionsResponse
}
var file_habit_v1_service_proto_depIdxs = []int32{
	0,  // 0: habit.v1.AuthService.Register:input_type -> habit.v1.RegisterRequest
	1,  // 1: habit.v1.AuthService.Login:input_type -> habit.v1.LoginRequest
	2,  // 2: habit.v1.AuthService.Refresh:input_type -> habit.v1.RefreshRequest
	3,  // 3: habit.v1.AuthService.Logout:input_type -> habit.v1.LogoutRequest
	4,  // 4: habit.v1.AuthService.Me:input_type -> habit.v1.MeRequest
	5,  // 5: habit.v1.HabitService.ListMachines:input_type -> habit.v1.ListMachinesRequest
	6,  // 6: habit.v1.HabitService.GetMachine:input_type -> habit.v1.GetMachineRequest
	7,  // 7: habit.v1.HabitService.CreateMachine:input_type -> habit.v1.CreateMachineRequest
	8,  // 8: habit.v1.HabitService.UpdateMachine:input_type -> habit.v1.UpdateMachineRequest
	9,  // 9: habit.v1.HabitService.DeleteMachine:input_type -> habit.v1.DeleteMachineRequest
	10, // 10: habit.v1.HabitService.ListExercises:input_type -> habit.v1.ListExercisesRequest
	11, // 11: habit.v1.HabitService.GetExercise:input_type -> habit.v1.GetExerciseRequest
	12, // 12: habit.v1.HabitService.CreateExercise:input_type -> habit.v1.CreateExerciseRequest
	13, // 13: habit.v1.HabitService.UpdateExercise:input_type -> habit.v1.UpdateExerciseRequest
	14, // 14: habit.v1.HabitService.ArchiveExercise:input_type -> habit.v1.ArchiveExerciseRequest
	15, // 15: habit.v1.HabitService.ListRoutines:input_type -> habit.v1.ListRoutinesRequest
	16, // 16: habit.v1.HabitService.GetRoutine:input_type -> habit.v1.GetRoutineRequest
	17, // 17: habit.v1.HabitService.CreateRoutine:input_type -> habit.v1.CreateRoutineRequest
	18, // 18: habit.v1.HabitService.UpdateRoutine:input_type -> habit.v1.UpdateRoutineRequest
	19, // 19: habit.v1.HabitService.ArchiveRoutine:input_type -> habit.v1.ArchiveRoutineRequest
	20, // 20: habit.v1.HabitService.StartRoutine:input_type -> habit.v1.StartRoutineRequest
	21, // 21: habit.v1.HabitService.EndRoutineRun:input_type -> habit.v1.EndRoutineRunRequest
	22, // 22: habit.v1.HabitService.LogSession:input_type -> habit.v1.LogSessionRequest
	23, // 23: habit.v1.HabitService.ListSessions:input_type -> habit.v1.ListSessionsRequest
	24, // 24: habit.v1.HabitService.UpdateSession:input_type -> habit.v1.UpdateSessionRequest
	25, // 25: habit.v1.HabitService.DeleteSession:input_type -> habit.v1.DeleteSessionRequest
	26, // 26: habit.v1.HabitService.GetWeeklyReport:input_type -> habit.v1.GetWeeklyReportRequest
	27, // 27: habit.v1.HabitService.GetMonthlyReport:input_type -> habit.v1.GetMonthlyReportRequest
	28, // 28: habit.v1.HabitService.ListProgressionSuggestions:input_type -> habit.v1.ListProgressionSuggestionsRequest
	29, // 29: habit.v1.AuthService.Register:output_type -> habit.v1.RegisterResponse
	30, // 30: habit.v1.AuthService.Login:output_type -> habit.v1.LoginResponse
	31, // 31: habit.v1.AuthService.Refresh:output_type -> habit.v1.RefreshResponse
	32, // 32: habit.v1.AuthService.Logout:output_type -> habit.v1.LogoutResponse
	33, // 33: habit.v1.AuthService.Me:output_type -> habit.v1.MeResponse
	34, // 34: habit.v1.HabitService.ListMachines:output_type -> habit.v1.ListMachinesResponse
	35, // 35: habit.v1.HabitService.GetMachine:output_type -> habit.v1.GetMachineResponse
	36, // 36: habit.v1.HabitService.CreateMachine:output_type -> habit.v1.CreateMachineResponse
	37, // 37: habit.v1.HabitService.UpdateMachine:output_type -> habit.v1.UpdateMachineResponse
	38, // 38: habit.v1.HabitService.DeleteMachine:output_type -> habit.v1.DeleteMachineResponse
	39, // 39: habit.v1.HabitService.ListExercises:output_type -> habit.v1.ListExercisesResponse
	40, // 40: habit.v1.HabitService.GetExercise:output_type -> habit.v1.GetExerciseResponse
	41, // 41: habit.v1.HabitService.CreateExercise:output_type -> habit.v1.CreateExerciseResponse
	42, // 42: habit.v1.HabitService.UpdateExercise:output_type -> habit.v1.UpdateExerciseResponse
	43, // 43: habit.v1.HabitService.ArchiveExercise:output_type -> habit.v1.ArchiveExerciseResponse
	44, // 44: habit.v1.HabitService.ListRoutines:output_type -> habit.v1.ListRoutinesResponse
	45, // 45: habit.v1.HabitService.GetRoutine:output_type -> habit.v1.GetRoutineResponse
	46, // 46: habit.v1.HabitService.CreateRoutine:output_type -> habit.v1.CreateRoutineResponse
	47, // 47: habit.v1.HabitService.UpdateRoutine:output_type -> habit.v1.UpdateRoutineResponse
	48, // 48: habit.v1.HabitService.ArchiveRoutine:output_type -> habit.v1.ArchiveRoutineResponse
	49, // 49: habit.v1.HabitService.StartRoutine:output_type -> habit.v1.StartRoutineResponse
	50, // 50: habit.v1.HabitService.EndRoutineRun:output_type -> habit.v1.EndRoutineRunResponse
	51, // 51: habit.v1.HabitService.LogSession:output_type -> habit.v1.LogSessionResponse
	52, // 52: habit.v1.HabitService.ListSessions:output_type -> habit.v1.ListSessionsResponse
	53, // 53: habit.v1.HabitService.UpdateSession:output_type -> habit.v1.UpdateSessionResponse
	54, // 54: habit.v1.HabitService.DeleteSession:output_type -> habit.v1.DeleteSessionResponse
	55, // 55: habit.v1.HabitService.GetWeeklyReport:output_type -> habit.v1.GetWeeklyReportResponse
	56, // 56: habit.v1.HabitService.GetMonthlyReport:output_type -> habit.v1.GetMonthlyReportResponse
	57, // 57: habit.v1.HabitService.ListProgressionSuggestions:output_type -> habit.v1.ListProgressionSuggestionsResponse
	29, // [29:58] is the sub-list for method output_type
	0,  // [0:29] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_habit_v1_service_proto_init() }
func file_habit_v1_service_proto_init() {
	if File_habit_v1_service_proto != nil {
		return
	}
	file_habit_v1_auth_proto_init()
	file_habit_v1_exercise_proto_init()
	file_habit_v1_machine_proto_init()
	file_habit_v1_report_proto_init()
	file_habit_v1_routine_proto_init()
	file_habit_v1_session_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_habit_v1_service_proto_rawDesc), len(file_habit_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_habit_v1_service_proto_goTypes,
		DependencyIndexes: file_habit_v1_service_proto_depIdxs,
	}.Build()
	File_habit_v1_service_proto = out.File
	file_habit_v1_service_proto_goTypes = nil
	file_habit_v1_service_proto_depIdxs = nil
}
