// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: habit/v1/session.proto

package habitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Session struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExerciseId      int64                  `protobuf:"varint,2,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	RoutineRunId    *int64                 `protobuf:"varint,3,opt,name=routine_run_id,json=routineRunId,proto3,oneof" json:"routine_run_id,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ended_at,json=endedAt,proto3,oneof" json:"ended_at,omitempty"`
	Status          SessionStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=habit.v1.SessionStatus" json:"status,omitempty"`
	CountCompleted  *int32                 `protobuf:"varint,7,opt,name=count_completed,json=countCompleted,proto3,oneof" json:"count_completed,omitempty"`
	CountGoal       *int32                 `protobuf:"varint,8,opt,name=count_goal,json=countGoal,proto3,oneof" json:"count_goal,omitempty"`
	DurationSeconds *int32                 `protobuf:"varint,9,opt,name=duration_seconds,json=durationSeconds,proto3,oneof" json:"duration_seconds,omitempty"`
	Difficulty      *Difficulty            `protobuf:"varint,10,opt,name=difficulty,proto3,enum=habit.v1.Difficulty,oneof" json:"difficulty,omitempty"`
	Notes           string                 `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	ClientId        string                 `protobuf:"bytes,12,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// 1-based set index for multi-set workouts; NULL/0 for logged-only kinds.
	SetIndex *int32 `protobuf:"varint,13,opt,name=set_index,json=setIndex,proto3,oneof" json:"set_index,omitempty"`
	// Planned set total at the time of logging (so reports can recover the plan).
	SetTotal *int32 `protobuf:"varint,14,opt,name=set_total,json=setTotal,proto3,oneof" json:"set_total,omitempty"`
	// Actual weight used (pounds) for weighted sessions.
	WeightLb      *float64 `protobuf:"fixed64,15,opt,name=weight_lb,json=weightLb,proto3,oneof" json:"weight_lb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_habit_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_habit_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Session) GetExerciseId() int64 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

func (x *Session) GetRoutineRunId() int64 {
	if x != nil && x.RoutineRunId != nil {
		return *x.RoutineRunId
	}
	return 0
}

func (x *Session) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Session) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Session) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *Session) GetCountCompleted() int32 {
	if x != nil && x.CountCompleted != nil {
		return *x.CountCompleted
	}
	return 0
}

func (x *Session) GetCountGoal() int32 {
	if x != nil && x.CountGoal != nil {
		return *x.CountGoal
	}
	return 0
}

func (x *Session) GetDurationSeconds() int32 {
	if x != nil && x.DurationSeconds != nil {
		return *x.DurationSeconds
	}
	return 0
}

func (x *Session) GetDifficulty() Difficulty {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return Difficulty_DIFFICULTY_UNSPECIFIED
}

func (x *Session) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Session) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Session) GetSetIndex() int32 {
	if x != nil && x.SetIndex != nil {
		return *x.SetIndex
	}
	return 0
}

func (x *Session) GetSetTotal() int32 {
	if x != nil && x.SetTotal != nil {
		return *x.SetTotal
	}
	return 0
}

func (x *Session) GetWeightLb() float64 {
	if x != nil && x.WeightLb != nil {
		return *x.WeightLb
	}
	return 0
}

type LogSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Idempotency key from frontend. Required.
	ClientId        string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ExerciseId      int64                  `protobuf:"varint,2,opt,name=exercise_id,json=exerciseId,proto3" json:"exercise_id,omitempty"`
	RoutineRunId    *int64                 `protobuf:"varint,3,opt,name=routine_run_id,json=routineRunId,proto3,oneof" json:"routine_run_id,omitempty"`
	StartedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	Status          SessionStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=habit.v1.SessionStatus" json:"status,omitempty"`
	CountCompleted  *int32                 `protobuf:"varint,7,opt,name=count_completed,json=countCompleted,proto3,oneof" json:"count_completed,omitempty"`
	CountGoal       *int32                 `protobuf:"varint,8,opt,name=count_goal,json=countGoal,proto3,oneof" json:"count_goal,omitempty"`
	DurationSeconds *int32                 `protobuf:"varint,9,opt,name=duration_seconds,json=durationSeconds,proto3,oneof" json:"duration_seconds,omitempty"`
	Difficulty      *Difficulty            `protobuf:"varint,10,opt,name=difficulty,proto3,enum=habit.v1.Difficulty,oneof" json:"difficulty,omitempty"`
	Notes           string                 `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	SetIndex        *int32                 `protobuf:"varint,12,opt,name=set_index,json=setIndex,proto3,oneof" json:"set_index,omitempty"`
	SetTotal        *int32                 `protobuf:"varint,13,opt,name=set_total,json=setTotal,proto3,oneof" json:"set_total,omitempty"`
	WeightLb        *float64               `protobuf:"fixed64,14,opt,name=weight_lb,json=weightLb,proto3,oneof" json:"weight_lb,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogSessionRequest) Reset() {
	*x = LogSessionRequest{}
	mi := &file_habit_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSessionRequest) ProtoMessage() {}

func (x *LogSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSessionRequest.ProtoReflect.Descriptor instead.
func (*LogSessionRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *LogSessionRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LogSessionRequest) GetExerciseId() int64 {
	if x != nil {
		return x.ExerciseId
	}
	return 0
}

func (x *LogSessionRequest) GetRoutineRunId() int64 {
	if x != nil && x.RoutineRunId != nil {
		return *x.RoutineRunId
	}
	return 0
}

func (x *LogSessionRequest) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *LogSessionRequest) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *LogSessionRequest) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *LogSessionRequest) GetCountCompleted() int32 {
	if x != nil && x.CountCompleted != nil {
		return *x.CountCompleted
	}
	return 0
}

func (x *LogSessionRequest) GetCountGoal() int32 {
	if x != nil && x.CountGoal != nil {
		return *x.CountGoal
	}
	return 0
}

func (x *LogSessionRequest) GetDurationSeconds() int32 {
	if x != nil && x.DurationSeconds != nil {
		return *x.DurationSeconds
	}
	return 0
}

func (x *LogSessionRequest) GetDifficulty() Difficulty {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return Difficulty_DIFFICULTY_UNSPECIFIED
}

func (x *LogSessionRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *LogSessionRequest) GetSetIndex() int32 {
	if x != nil && x.SetIndex != nil {
		return *x.SetIndex
	}
	return 0
}

func (x *LogSessionRequest) GetSetTotal() int32 {
	if x != nil && x.SetTotal != nil {
		return *x.SetTotal
	}
	return 0
}

func (x *LogSessionRequest) GetWeightLb() float64 {
	if x != nil && x.WeightLb != nil {
		return *x.WeightLb
	}
	return 0
}

type LogSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogSessionResponse) Reset() {
	*x = LogSessionResponse{}
	mi := &file_habit_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSessionResponse) ProtoMessage() {}

func (x *LogSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSessionResponse.ProtoReflect.Descriptor instead.
func (*LogSessionResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *LogSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3,oneof" json:"to,omitempty"`
	ExerciseId    *int64                 `protobuf:"varint,3,opt,name=exercise_id,json=exerciseId,proto3,oneof" json:"exercise_id,omitempty"`
	RoutineRunId  *int64                 `protobuf:"varint,4,opt,name=routine_run_id,json=routineRunId,proto3,oneof" json:"routine_run_id,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_habit_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *ListSessionsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ListSessionsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ListSessionsRequest) GetExerciseId() int64 {
	if x != nil && x.ExerciseId != nil {
		return *x.ExerciseId
	}
	return 0
}

func (x *ListSessionsRequest) GetRoutineRunId() int64 {
	if x != nil && x.RoutineRunId != nil {
		return *x.RoutineRunId
	}
	return 0
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_habit_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// UpdateSessionRequest patches an already-logged session. All fields except
// `id` are optional; only fields explicitly set in the request are written.
// The exercise_id, routine_run_id and client_id of the row never change.
type UpdateSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status          *SessionStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=habit.v1.SessionStatus,oneof" json:"status,omitempty"`
	CountCompleted  *int32                 `protobuf:"varint,3,opt,name=count_completed,json=countCompleted,proto3,oneof" json:"count_completed,omitempty"`
	DurationSeconds *int32                 `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3,oneof" json:"duration_seconds,omitempty"`
	Difficulty      *Difficulty            `protobuf:"varint,5,opt,name=difficulty,proto3,enum=habit.v1.Difficulty,oneof" json:"difficulty,omitempty"`
	Notes           *string                `protobuf:"bytes,6,opt,name=notes,proto3,oneof" json:"notes,omitempty"`
	WeightLb        *float64               `protobuf:"fixed64,7,opt,name=weight_lb,json=weightLb,proto3,oneof" json:"weight_lb,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_habit_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSessionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSessionRequest) GetStatus() SessionStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *UpdateSessionRequest) GetCountCompleted() int32 {
	if x != nil && x.CountCompleted != nil {
		return *x.CountCompleted
	}
	return 0
}

func (x *UpdateSessionRequest) GetDurationSeconds() int32 {
	if x != nil && x.DurationSeconds != nil {
		return *x.DurationSeconds
	}
	return 0
}

func (x *UpdateSessionRequest) GetDifficulty() Difficulty {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return Difficulty_DIFFICULTY_UNSPECIFIED
}

func (x *UpdateSessionRequest) GetNotes() string {
	if x != nil && x.Notes != nil {
		return *x.Notes
	}
	return ""
}

func (x *UpdateSessionRequest) GetWeightLb() float64 {
	if x != nil && x.WeightLb != nil {
		return *x.WeightLb
	}
	return 0
}

type UpdateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSessionResponse) Reset() {
	*x = UpdateSessionResponse{}
	mi := &file_habit_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionResponse) ProtoMessage() {}

func (x *UpdateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSessionResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_habit_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_habit_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSessionRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_habit_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_habit_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_habit_v1_session_proto_rawDescGZIP(), []int{8}
}

var File_habit_v1_session_proto protoreflect.FileDescriptor

const file_habit_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x16habit/v1/session.proto\x12\bhabit.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15habit/v1/common.proto\"\xf4\x05\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vexercise_id\x18\x02 \x01(\x03R\n" +
	"exerciseId\x12)\n" +
	"\x0eroutine_run_id\x18\x03 \x01(\x03H\x00R\froutineRunId\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12:\n" +
	"\bended_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendedAt\x88\x01\x01\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x17.habit.v1.SessionStatusR\x06status\x12,\n" +
	"\x0fcount_completed\x18\a \x01(\x05H\x02R\x0ecountCompleted\x88\x01\x01\x12\"\n" +
	"\n" +
	"count_goal\x18\b \x01(\x05H\x03R\tcountGoal\x88\x01\x01\x12.\n" +
	"\x10duration_seconds\x18\t \x01(\x05H\x04R\x0fdurationSeconds\x88\x01\x01\x129\n" +
	"\n" +
	"difficulty\x18\n" +
	" \x01(\x0e2\x14.habit.v1.DifficultyH\x05R\n" +
	"difficulty\x88\x01\x01\x12\x14\n" +
	"\x05notes\x18\v \x01(\tR\x05notes\x12\x1b\n" +
	"\tclient_id\x18\f \x01(\tR\bclientId\x12 \n" +
	"\tset_index\x18\r \x01(\x05H\x06R\bsetIndex\x88\x01\x01\x12 \n" +
	"\tset_total\x18\x0e \x01(\x05H\aR\bsetTotal\x88\x01\x01\x12 \n" +
	"\tweight_lb\x18\x0f \x01(\x01H\bR\bweightLb\x88\x01\x01B\x11\n" +
	"\x0f_routine_run_idB\v\n" +
	"\t_ended_atB\x12\n" +
	"\x10_count_completedB\r\n" +
	"\v_count_goalB\x13\n" +
	"\x11_duration_secondsB\r\n" +
	"\v_difficultyB\f\n" +
	"\n" +
	"_set_indexB\f\n" +
	"\n" +
	"_set_totalB\f\n" +
	"\n" +
	"_weight_lb\"\xdc\x05\n" +
	"\x11LogSessionRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vexercise_id\x18\x02 \x01(\x03R\n" +
	"exerciseId\x12)\n" +
	"\x0eroutine_run_id\x18\x03 \x01(\x03H\x00R\froutineRunId\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x17.habit.v1.SessionStatusR\x06status\x12,\n" +
	"\x0fcount_completed\x18\a \x01(\x05H\x01R\x0ecountCompleted\x88\x01\x01\x12\"\n" +
	"\n" +
	"count_goal\x18\b \x01(\x05H\x02R\tcountGoal\x88\x01\x01\x12.\n" +
	"\x10duration_seconds\x18\t \x01(\x05H\x03R\x0fdurationSeconds\x88\x01\x01\x129\n" +
	"\n" +
	"difficulty\x18\n" +
	" \x01(\x0e2\x14.habit.v1.DifficultyH\x04R\n" +
	"difficulty\x88\x01\x01\x12\x14\n" +
	"\x05notes\x18\v \x01(\tR\x05notes\x12 \n" +
	"\tset_index\x18\f \x01(\x05H\x05R\bsetIndex\x88\x01\x01\x12 \n" +
	"\tset_total\x18\r \x01(\x05H\x06R\bsetTotal\x88\x01\x01\x12 \n" +
	"\tweight_lb\x18\x0e \x01(\x01H\aR\bweightLb\x88\x01\x01B\x11\n" +
	"\x0f_routine_run_idB\x12\n" +
	"\x10_count_completedB\r\n" +
	"\v_count_goalB\x13\n" +
	"\x11_duration_secondsB\r\n" +
	"\v_difficultyB\f\n" +
	"\n" +
	"_set_indexB\f\n" +
	"\n" +
	"_set_totalB\f\n" +
	"\n" +
	"_weight_lb\"A\n" +
	"\x12LogSessionResponse\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.habit.v1.SessionR\asession\"\x95\x02\n" +
	"\x13ListSessionsRequest\x123\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x04from\x88\x01\x01\x12/\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x02to\x88\x01\x01\x12$\n" +
	"\vexercise_id\x18\x03 \x01(\x03H\x02R\n" +
	"exerciseId\x88\x01\x01\x12)\n" +
	"\x0eroutine_run_id\x18\x04 \x01(\x03H\x03R\froutineRunId\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limitB\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_toB\x0e\n" +
	"\f_exercise_idB\x11\n" +
	"\x0f_routine_run_id\"E\n" +
	"\x14ListSessionsResponse\x12-\n" +
	"\bsessions\x18\x01 \x03(\v2\x11.habit.v1.SessionR\bsessions\"\x8d\x03\n" +
	"\x14UpdateSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.habit.v1.SessionStatusH\x00R\x06status\x88\x01\x01\x12,\n" +
	"\x0fcount_completed\x18\x03 \x01(\x05H\x01R\x0ecountCompleted\x88\x01\x01\x12.\n" +
	"\x10duration_seconds\x18\x04 \x01(\x05H\x02R\x0fdurationSeconds\x88\x01\x01\x129\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x14.habit.v1.DifficultyH\x03R\n" +
	"difficulty\x88\x01\x01\x12\x19\n" +
	"\x05notes\x18\x06 \x01(\tH\x04R\x05notes\x88\x01\x01\x12 \n" +
	"\tweight_lb\x18\a \x01(\x01H\x05R\bweightLb\x88\x01\x01B\t\n" +
	"\a_statusB\x12\n" +
	"\x10_count_completedB\x13\n" +
	"\x11_duration_secondsB\r\n" +
	"\v_difficultyB\b\n" +
	"\x06_notesB\f\n" +
	"\n" +
	"_weight_lb\"D\n" +
	"\x15UpdateSessionResponse\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.habit.v1.SessionR\asession\"&\n" +
	"\x14DeleteSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x17\n" +
	"\x15DeleteSessionResponseB\x9c\x01\n" +
	"\fcom.habit.v1B\fSessionProtoP\x01Z=github.com/geekgonecrazy/training-log/models/habit/v1;habitv1\xa2\x02\x03HXX\xaa\x02\bHabit.V1\xca\x02\bHabit\\V1\xe2\x02\x14Habit\\V1\\GPBMetadata\xea\x02\tHabit::V1b\x06proto3"

var (
	file_habit_v1_session_proto_rawDescOnce sync.Once
	file_habit_v1_session_proto_rawDescData []byte
)

func file_habit_v1_session_proto_rawDescGZIP() []byte {
	file_habit_v1_session_proto_rawDescOnce.Do(func() {
		file_habit_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_habit_v1_session_proto_rawDesc), len(file_habit_v1_session_proto_rawDesc)))
	})
	return file_habit_v1_session_proto_rawDescData
}

var file_habit_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_habit_v1_session_proto_goTypes = []any{
	(*Session)(nil),               // 0: habit.v1.Session
	(*LogSessionRequest)(nil),     // 1: habit.v1.LogSessionRequest
	(*LogSessionResponse)(nil),    // 2: habit.v1.LogSessionResponse
	(*ListSessionsRequest)(nil),   // 3: habit.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 4: habit.v1.ListSessionsResponse
	(*UpdateSessionRequest)(nil),  // 5: habit.v1.UpdateSessionRequest
	(*UpdateSessionResponse)(nil), // 6: habit.v1.UpdateSessionResponse
	(*DeleteSessionRequest)(nil),  // 7: habit.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil), // 8: habit.v1.DeleteSessionResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(SessionStatus)(0),            // 10: habit.v1.SessionStatus
	(Difficulty)(0),               // 11: habit.v1.Difficulty
}
var file_habit_v1_session_proto_depIdxs = []int32{
	9,  // 0: habit.v1.Session.started_at:type_name -> google.protobuf.Timestamp
	9,  // 1: habit.v1.Session.ended_at:type_name -> google.protobuf.Timestamp
	10, // 2: habit.v1.Session.status:type_name -> habit.v1.SessionStatus
	11, // 3: habit.v1.Session.difficulty:type_name -> habit.v1.Difficulty
	9,  // 4: habit.v1.LogSessionRequest.started_at:type_name -> google.protobuf.Timestamp
	9,  // 5: habit.v1.LogSessionRequest.ended_at:type_name -> google.protobuf.Timestamp
	10, // 6: habit.v1.LogSessionRequest.status:type_name -> habit.v1.SessionStatus
	11, // 7: habit.v1.LogSessionRequest.difficulty:type_name -> habit.v1.Difficulty
	0,  // 8: habit.v1.LogSessionResponse.session:type_name -> habit.v1.Session
	9,  // 9: habit.v1.ListSessionsRequest.from:type_name -> google.protobuf.Timestamp
	9,  // 10: habit.v1.ListSessionsRequest.to:type_name -> google.protobuf.Timestamp
	0,  // 11: habit.v1.ListSessionsResponse.sessions:type_name -> habit.v1.Session
	10, // 12: habit.v1.UpdateSessionRequest.status:type_name -> habit.v1.SessionStatus
	11, // 13: habit.v1.UpdateSessionRequest.difficulty:type_name -> habit.v1.Difficulty
	0,  // 14: habit.v1.UpdateSessionResponse.session:type_name -> habit.v1.Session
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_habit_v1_session_proto_init() }
func file_habit_v1_session_proto_init() {
	if File_habit_v1_session_proto != nil {
		return
	}
	file_habit_v1_common_proto_init()
	file_habit_v1_session_proto_msgTypes[0].OneofWrappers = []any{}
	file_habit_v1_session_proto_msgTypes[1].OneofWrappers = []any{}
	file_habit_v1_session_proto_msgTypes[3].OneofWrappers = []any{}
	file_habit_v1_session_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_habit_v1_session_proto_rawDesc), len(file_habit_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_habit_v1_session_proto_goTypes,
		DependencyIndexes: file_habit_v1_session_proto_depIdxs,
		MessageInfos:      file_habit_v1_session_proto_msgTypes,
	}.Build()
	File_habit_v1_session_proto = out.File
	file_habit_v1_session_proto_goTypes = nil
	file_habit_v1_session_proto_depIdxs = nil
}
